---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-feature-discovery
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: gpu-feature-discovery-charts
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/pci-10de.present
                  operator: In
                  values:
                    - "true"
    migStrategy: none
    nfd:
      deploy: false

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gpu-feature-discovery-charts
spec:
  interval: 1h
  url: https://nvidia.github.io/gpu-feature-discovery
