---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gpu-feature-discovery-charts
spec:
  interval: 1h
  url: https://nvidia.github.io/gpu-feature-discovery
