---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey
spec:
  refreshPolicy: CreatedOnce
  target:
    name: valkey-secret
    creationPolicy: Orphan
    template:
      engineVersion: v2
      data:
        VALKEY_PASSWORD: "{{ .VALKEY_PASSWORD }}"
        REDIS_URL: "redis://:{{ .VALKEY_PASSWORD }}@valkey.default.svc.cluster.local:6379/0"
        VALKEY_URL: "redis://:{{ .VALKEY_PASSWORD }}@valkey.default.svc.cluster.local:6379/0"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: valkey-password
