---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hindsight
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hindsight-secret
    template:
      data:
        postgres-password: "{{ .HINDSIGHT_POSTGRES_PASSWORD }}"
        POSTGRES_PASSWORD_URI: "{{ .HINDSIGHT_POSTGRES_PASSWORD | urlquery }}"
        HINDSIGHT_API_EMBEDDINGS_LITELLM_SDK_API_KEY: "{{ .VOYAGE_API_KEY }}"
        HINDSIGHT_API_LLM_API_KEY: "spark-local"
        HINDSIGHT_CP_ACCESS_KEY: "{{ .HINDSIGHT_CP_ACCESS_KEY }}"
        HINDSIGHT_API_OTEL_EXPORTER_OTLP_HEADERS: "{{ .HINDSIGHT_API_OTEL_EXPORTER_OTLP_HEADERS }}"
  dataFrom:
    - extract:
        key: hindsight
    - extract:
        key: postgres
