---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: minio-passwords
spec:
  length: 48
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - MINIO_ROOT_PASSWORD
    - MINIO_LANGFUSE_SECRET_KEY
    - MINIO_PAPERCLIP_SECRET_KEY
    - MINIO_OPEN_WEBUI_SECRET_KEY
