---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperclip
spec:
  refreshPolicy: CreatedOnce
  target:
    name: paperclip-secret
    creationPolicy: Orphan
    template:
      engineVersion: v2
      data:
        BETTER_AUTH_SECRET: "{{ .BETTER_AUTH_SECRET }}"
        PAPERCLIP_SECRETS_MASTER_KEY: "{{ .PAPERCLIP_SECRETS_MASTER_KEY }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: paperclip-passwords
