---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: paperclip-passwords
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - BETTER_AUTH_SECRET
    - PAPERCLIP_SECRETS_MASTER_KEY
