---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-feature-discovery
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: gpu-feature-discovery-charts
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/pci-10de.present
                  operator: In
                  values:
                    - "true"
    migStrategy: none
    nfd:
      deploy: false
    runtimeClassName: nvidia
