---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unsloth-studio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unsloth-studio-secret
    template:
      data:
        JUPYTER_PASSWORD: "{{ .JUPYTER_PASSWORD }}"
  data:
    - secretKey: JUPYTER_PASSWORD
      remoteRef:
        key: unsloth-studio
        property: JUPYTER_PASSWORD
