---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: langfuse-secret
    template:
      data:
        salt: "{{ .SALT }}"
        encryption-key: "{{ .ENCRYPTION_KEY }}"
        nextauth-secret: "{{ .NEXTAUTH_SECRET }}"
        postgresql-password: "{{ .POSTGRESQL_PASSWORD }}"
        clickhouse-password: "{{ .CLICKHOUSE_PASSWORD }}"
        redis-password: "{{ .REDIS_PASSWORD }}"
        s3-user: "{{ .S3_USER }}"
        s3-password: "{{ .S3_PASSWORD }}"
  dataFrom:
    - extract:
        key: langfuse
