---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: langfuse-secret
    template:
      data:
        salt: "{{ .SALT }}"
        encryption-key: "{{ .ENCRYPTION_KEY }}"
        nextauth-secret: "{{ .NEXTAUTH_SECRET }}"
        LANGFUSE_POSTGRES_PASSWORD: "{{ .LANGFUSE_POSTGRES_PASSWORD }}"
        clickhouse-password: "{{ .CLICKHOUSE_PASSWORD }}"
        VALKEY_PASSWORD: "{{ .VALKEY_PASSWORD }}"
        MINIO_LANGFUSE_ACCESS_KEY: "langfuse"
        MINIO_LANGFUSE_SECRET_KEY: "{{ .MINIO_LANGFUSE_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: langfuse
    - extract:
        key: postgres
    - extract:
        key: valkey
    - extract:
        key: minio
