---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sillytavern
spec:
  chartRef:
    kind: OCIRepository
    name: sillytavern
  interval: 1h
  values:
    controllers:
      sillytavern:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/sillytavern/sillytavern
              tag: staging@sha256:3e0fcfb982f32271f605861e664a8d44a0aa7993e6e1b19e91e476e883a0b2e2
            env:
              TZ: America/New_York
              SILLYTAVERN_LISTEN: "true"
              SILLYTAVERN_WHITELIST: '["::/0", "0.0.0.0/0"]'
              SILLYTAVERN_PORT: &port 80
              SILLYTAVERN_HEARTBEATINTERVAL: "30"
              SILLYTAVERN_ENABLESERVERPLUGINS: "true"
              SILLYTAVERN_EXTENSIONS_MODELS_CLASSIFICATION: "SamLowe/roberta-base-go_emotions-onnx"
              SILLYTAVERN_EXTENSIONS_MODELS_EMBEDDING: "mixedbread-ai/mxbai-embed-large-v1"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command: [node, src/healthcheck.js]
                  initialDelaySeconds: 20
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.hades.casa"
          - tavern.hades.casa
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /home/node/app/config
            subPath: config
          - path: /home/node/app/data
            subPath: data
          - path: /home/node/app/plugins
            subPath: plugins
          - path: /home/node/app/public/scripts/extensions/third-party
            subPath: extensions
      tmp:
        type: emptyDir
        medium: Memory
        sizeLimit: 64Mi
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /home/node/app/backups
            subPath: backups
