---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    template:
      data:
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
        OPEN_WEBUI_DATABASE_URL: "postgresql://open_webui:{{ .OPEN_WEBUI_POSTGRES_PASSWORD }}@postgres.database.svc.cluster.local:5432/open_webui"
  dataFrom:
    - extract:
        key: open-webui
    - extract:
        key: postgres
