---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  refreshPolicy: CreatedOnce
  target:
    name: postgres-secret
    creationPolicy: Orphan
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "postgres"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        HINDSIGHT_POSTGRES_PASSWORD: "{{ .HINDSIGHT_POSTGRES_PASSWORD }}"
        LANGFUSE_POSTGRES_PASSWORD: "{{ .LANGFUSE_POSTGRES_PASSWORD }}"
        PAPERCLIP_POSTGRES_PASSWORD: "{{ .PAPERCLIP_POSTGRES_PASSWORD }}"
        OPEN_WEBUI_POSTGRES_PASSWORD: "{{ .OPEN_WEBUI_POSTGRES_PASSWORD }}"
        HINDSIGHT_DATABASE_URL: "postgresql://hindsight:{{ .HINDSIGHT_POSTGRES_PASSWORD }}@postgres.default.svc.cluster.local:5432/hindsight"
        LANGFUSE_DATABASE_URL: "postgresql://langfuse:{{ .LANGFUSE_POSTGRES_PASSWORD }}@postgres.default.svc.cluster.local:5432/langfuse"
        PAPERCLIP_DATABASE_URL: "postgresql://paperclip:{{ .PAPERCLIP_POSTGRES_PASSWORD }}@postgres.default.svc.cluster.local:5432/paperclip"
        OPEN_WEBUI_DATABASE_URL: "postgresql://open_webui:{{ .OPEN_WEBUI_POSTGRES_PASSWORD }}@postgres.default.svc.cluster.local:5432/open_webui"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: postgres-passwords








