---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: postgres-passwords
spec:
  length: 48
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - POSTGRES_PASSWORD
    - HINDSIGHT_POSTGRES_PASSWORD
    - LANGFUSE_POSTGRES_PASSWORD
    - PAPERCLIP_POSTGRES_PASSWORD
    - OPEN_WEBUI_POSTGRES_PASSWORD
