---
apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
  annotations:
    lbipam.cilium.io/ips: 10.8.0.131
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
