---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vllm
spec:
  interval: 30m
  timeout: 30m
  chart:
    spec:
      chart: vllm-stack
      version: 0.1.10
      sourceRef:
        kind: HelmRepository
        name: vllm
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  valuesFrom:
    - kind: Secret
      name: vllm-secret
      valuesKey: HF_TOKEN
      targetPath: servingEngineSpec.modelSpec[0].hf_token

  values:
    routerSpec:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          memory: 500Mi
        limits:
          memory: 2Gi
      route:
        main:
          enabled: true
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          hostnames:
            - vllm.hades.casa
          parentRefs:
            - name: envoy-internal
              namespace: network

    servingEngineSpec:
      runtimeClassName: nvidia
      strategy:
        type: Recreate

      modelSpec:
        - name: qwen-3-5-9b
          repository: vllm/vllm-openai
          tag: nightly@sha256:97aaaad8846ebf431b6ac2ee2fc24dec7791c6405393f450e970f9a2d60739c4
          modelURL: DavidAU/Qwen3.5-9B-Deckard-Claude-DIMOE-Uncensored-Heretic-Thinking
          replicaCount: 1

          requestCPU: 4
          requestMemory: 2Gi
          limitMemory: 24Gi
          requestGPU: 1

          pvcStorage: 50Gi
          pvcAccessMode:
            - ReadWriteOnce

          vllmConfig:
            extraArgs:
              - "--enforce-eager"
              - "--max-model-len"
              - "262144"
              - "--reasoning-parser"
              - "qwen3"
              - "--override-generation-config"
              - '{"temperature":1.0,"top_p":0.95,"top_k":20,"min_p":0.0,"presence_penalty":1.5,"repetition_penalty":1.0}'

          shmSize: 8Gi

          env:
            - name: TZ
              value: America/New_York
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
            - name: NVIDIA_VISIBLE_DEVICES
              value: all

          nodeSelector:
            nvidia.feature.node.kubernetes.io/gpu: "true"

          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule

    observabilitySpec:
      enabled: true
      serviceMonitor:
        enabled: true
