---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "postgres"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        HINDSIGHT_POSTGRES_PASSWORD: "{{ .HINDSIGHT_POSTGRES_PASSWORD }}"
        LANGFUSE_POSTGRES_PASSWORD: "{{ .LANGFUSE_POSTGRES_PASSWORD }}"
        OPEN_WEBUI_POSTGRES_PASSWORD: "{{ .OPEN_WEBUI_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: postgres
