---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minio-secret
    template:
      engineVersion: v2
      data:
        MINIO_ROOT_USER: "minio-root"
        MINIO_ROOT_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
        MINIO_LANGFUSE_ACCESS_KEY: "langfuse"
        MINIO_LANGFUSE_SECRET_KEY: "{{ .MINIO_LANGFUSE_SECRET_KEY }}"
        MINIO_OPEN_WEBUI_ACCESS_KEY: "open-webui"
        MINIO_OPEN_WEBUI_SECRET_KEY: "{{ .MINIO_OPEN_WEBUI_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: minio
